name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
        
      - name: Install Dependencies
        run: yarn
        working-directory: ${{env.working-directory}}
        
      - name: Build
        run: yarn build
        working-directory: ${{env.working-directory}}
        
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }} 
          source: "backend, !backend/node_modules"
          target: "~/apps/carmbi-api"

      - name: Update API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/apps/carmbi-api/backend
            yarn
            yarn prisma migrate dev
            pm2 restart carmbi_api
        
